Added analysis from min_height
SEFGroup23/assignment3-coverage pull request #32
Opened 2022-02-19 13:32 UTC by HakuPiku

Solves #30

2022-02-20 11:19 UTC, capitanu requested changes

2022-02-20 11:19 UTC, capitanu commented on manual_evaluations/part1_complexity/min_height.py
> +# 5. Note at all. There's no documentation at all.
I think there's a type here. You probably mean "Not at all"

2022-02-20 11:19 UTC, capitanu commented on manual_evaluations/part1_complexity/min_height.py
> +# 3. This function is supposed to count the minimum height of a tree. It is supposed to be return 0 if root Node is None. If right or left Node is None, the height is 1, and so on it keeps checking r
Could you please not have lines longer than 80 characters as this is standard? I know this is nit-picking, but it becomes hard to read even here on github and on most editors that do not truncate lines by default.

2022-02-20 17:21 UTC, ArnPellesGit approved these changes
LGTM

2022-02-21 20:35 UTC, capitanu approved these changes

2022-02-22 16:23 UTC, merged